// Map keys to labels.
export const Regions = {
    "Abruzzo": "Abruzzo",
    "Basilicata": "Basilicata",
    "Calabria": "Calabria",
    "Campania": "Campania",
    "Emilia_Romagna": "Emilia-Romagna",
    "Friuli_Venezia_Giulia": "Friuli-Venezia Giulia",
    "Lazio": "Lazio",
    "Liguria": "Liguria",
    "Lombardia": "Lombardia",
    "Marche": "Marche",
    "Molise": "Molise",
    "Piemonte": "Piemonte",
    "Puglia": "Puglia",
    "Sardegna": "Sardegna",
    "Sicilia": "Sicilia",
    "Toscana": "Toscana",
    "Trentino_Alto_Adige": "Trentino-Alto Adige",
    "Umbria": "Umbria",
    "Valle_d_Aosta": "Valle d'Aosta",
    "Veneto": "Veneto",
};